let questions=[
	{
		numb:1,
		question:" What kind of list is best to answer many questions such as “what is the item at position n?",
		answer:"Lists implemented with an array",
		options:[
			"Singly-linked lists",
			"Doubly-linked lists",
			"Circular- linked lists",
			"Lists implemented with an array"
		]
	},
	{
		numb:2,
		question:"Which of following operations are generally not performed on report files?",
		answer:"All of above",
		options:[
			"Updation",
			" Maintenance",
			"Retrieval",
			"All of above"
		]
	},
	{
		numb:3,
		question:"A data item that can be used to distinguish between two entities (records) is known as",
		answer:" Primary key",
		options:[
			"Alternate key",
			" Primary key",
			"Primary data item",
			"Unique data item"
		]
	},
	{
		numb:4,
		question:"When is insertion sort a good choice for sorting an array?",
		answer:"The array has only a few elements out of place",
		options:[
			"The array has only a few elements out of place",
			"Each element of array requires a small amount of memory",
			"The processor speed is fast",
			"Each element of array requires a large amount of memory"
		]
	},
	{
		numb:5,
		question:"What is the number of nodes in a full binary tree with depth 3?",
		answer:"7",
		options:[
			"5",
			"8",
			"9",
			"7"
		]
	},
	{
		numb:6,
		question:"Which of the following is not an entity?",
		answer:"Roll number",
		options:[
			"Employee",
			"Student",
			"Book",
			"Roll number"
		]
	},
	{
		numb:7,
		question:"An enqueue operation adds an element",
		answer:" To the rear of the queue",
		options:[
			"At any position in the queue",
			" To the front of the queue",
			" To the rear of the queue",
			"None of above"
		]
	},
	{
		numb:8,
		question:"What is the minimum number of nodes in a complete binary tree with depth 3?",
		answer:" 4",
		options:[
			"3",
			"5",
			"2",
			" 4"
		]
	},
	{
		numb:9,
		question:"A dequeue operation removes an element",
		answer:"From the front of the queue",
		options:[
			"From the front of the queue",
			"From any place in the queue",
			"From the rear of the queue",
			"None of above"
		]
	},
	{
		numb:10,
		question:"The average case complexity of quick sort for sorting n numbers is",
		answer:"O(nlog2n)",
		options:[
			" O(n2)",
			"O(nlog2n)",
			"O(n)",
			" O(log2n)"
		]
	},
];